## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - nightly

notifications:
  email: false

git:
  depth: 99999999

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - pwd
  - ls
  - julia --check-bounds=yes -e 'using UUIDs; write("Project.toml", replace(read("Project.toml", String), r"uuid = .*?\n" =>"uuid = \"$(uuid4())\"")); import Pkg; Pkg.instantiate(); Pkg.test("Shell"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("Shell")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("Shell")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
